### ISSUE TITLE
Metric System?

### ISSUE THREAD

**Issue by radiodario** [elliotstokes/gpx-parse#10]
Hi there, thank you so much for this library, it's super useful.

Is there an option for the parser to return km rather than miles? I see the software is hard-coded to use miles for distances (track lengths etc) but meters for elevations. Wouldn't it make more sense to return *everything* in metric or everything in imperial?

if so, would you accept a PR that defaults to metric?

Thanks

Dario

**Comment by elliotstokes** [comment]
Hey. Yeah I think the best would be to return metric. Sure I would accept a PR. Maybe it should optionally accept a flag to return in imperial if a user wanted it to.

**Comment by elliotstokes** [comment]
If I get chance I will implement tonight. If not I would be happy for you to do it. It should be pretty easy. Its just  matter of calculating with the great circle radius in km instead I think

**Comment by radiodario** [comment]
No no, hold your horses, i've implemented it on my fork and updated the tests :)

**Comment by elliotstokes** [comment]
Brilliant. Thanks a lot

**Comment by radiodario** [comment]
i've just added a PR

**Comment by elliotstokes** [comment]
Brilliant. Ill add the broserify command into the package.json. all looks good will commit now.
