### ISSUE TITLE
GpxWaypoint Elevation is an array

### ISSUE THREAD

**Issue by cspeer** [elliotstokes/gpx-parse#12]
Hi there,

http://www.vapidspace.com/gpx-parse/doc/GpxWaypoint.html states that member `elevation` is a number. However, when I parse a GPX file I get an array with only a single item which then is a number.

Thanks so much for this parser. I have been looking for one for quite some time now!

Thanks,
Chris

**Comment by elliotstokes** [comment]
ok. Ill look into this. Are you using gpx v1.1 or 1.0?

**Comment by cspeer** [comment]
Not sure, your package.json says it's 0.9.0 but I didn't install via npm, I copied the file from https://github.com/elliotstokes/gpx-parse/blob/master/dist/gpx-parse-browser.js

Thanks!!!

**Comment by elliotstokes** [comment]
Sorry the version of gpx that you are using i think there are two v1.0 or 1.1.

**Comment by cspeer** [comment]
1.0

Thanks!!

**Comment by cspeer** [comment]
Yeah, I only realised what you meant a few seconds after posting :D

**Comment by elliotstokes** [comment]
Ok im also seeing this. ill fix and release a new version.

**Comment by cspeer** [comment]
Awesome, thanks so much!
On another note: Would you mind adding a bower.json?

**Comment by elliotstokes** [comment]
fixed in a7dc6ff207388260b2b4b167ac4aaa37f7fd05e5

**Comment by cspeer** [comment]
Thank you!!

**Comment by elliotstokes** [comment]
I have added a bower.json too

**Comment by elliotstokes** [comment]
have also now published to npm. Hope that helps.

**Comment by cspeer** [comment]
Can't say thanks enough

**Comment by cspeer** [comment]
Ah, one more thing:
Can you please register the package with bower? http://bower.io/docs/creating-packages/
Thanks :)

**Comment by elliotstokes** [comment]
done. :)
