### ISSUE TITLE
GPX with only waypoints

### ISSUE THREAD

**Issue by cspeer** [elliotstokes/gpx-parse#13]
Hi again,

I have a .gpx file which only contains waypoints. When I try to parse it I get a `TypeError: Cannot read property 'length' of undefined`. Usually I would post the contents of the file, but in this case they contain commercial property, so... do you mind if I send it to you via email?

Thanks,
Chris

**Comment by elliotstokes** [comment]
Yeah sure. i think my email should be attached to my account. if not then let me know.

**Comment by elliotstokes** [comment]
actually im not sure it is. try elliot.stokes___@___gmail.com without the underscores.

**Comment by elliotstokes** [comment]
This should now be fixed, however if you have some sample gpx you don't mind sharing I wouldn't mind still taking a copy to make some further improvements

**Comment by cspeer** [comment]
Awesome! Thank you.
Would you mind also updating the browser version in dist/?
I'll send you a bunch more via email :)

Cheers!
