### ISSUE TITLE
Bower Usage

### ISSUE THREAD

**Issue by cspeer** [elliotstokes/gpx-parse#14]
Hi,

when I use the lib via bower, there are no errors thrown, but the `gpxParse` is not available.
I'm not sure but I think if the `index.js` does not actually load all modules the `bower.json` should point to a compiled version for the browser in its main attribute.

Thanks,
Chris

**Comment by elliotstokes** [comment]
Ah ok the index.js is for use within node. If you are using it in the browser you need to use the file within the dist folder.

Ill change bower to point to that instead.

**Comment by elliotstokes** [comment]
Ok I hadnt drafted a release so bower was getting a really old version (not published anything to bower before. Sorry). if you download again from bower you should now get the dist folder. Let me know how you get on with that.

**Comment by cspeer** [comment]
Well, now I get the following error in the browser:
`module.exports = process.env.GPXPARSE_COV ? require('./lib-cov/gpx-parse') : require('./lib/gpx-parse');`

**Comment by cspeer** [comment]
Maybe you are right and I really shouldn't handle the parsing in the user's browser though

**Comment by elliotstokes** [comment]
are you using the file in the dist folder? dont use the index.js on the client.

**Comment by cspeer** [comment]
Yeah, the bower.json still points to index.js in "main"

**Comment by elliotstokes** [comment]
i have pointed it to the file in dist now. See how you get on with that.

**Comment by cspeer** [comment]
Whoop whoop, that works.
Thanks a lot, Elliot!

**Comment by elliotstokes** [comment]
thanks. Any other problems let me know - it's nice to know people are getting some use out of it!

**Comment by cspeer** [comment]
oh I'm getting a lot of use out of it. I was so happy when I discovered
your lib! Saves me so much time.
