### ISSUE TITLE
Missing `lib-cov`

### ISSUE THREAD

**Issue by akoenig** [elliotstokes/gpx-parse#3]
Hey Elliot,

thanks for writing and sharing `gpx-parse`. Works great in Node.js!

I tried to `browserify` your module so that I can use it in the browser as well without any API modifications. Unfortunately that did not work. There are missing source files in the repository. The culprit is the ternary operator within [index.js](https://github.com/elliotstokes/gpx-parse/blob/29cc582d4fd469130a285ac3a1a7c19db2bfec38/index.js#L1).

Browserify fails here because it seeks for all `require` statements in order to embed the dependencies. The first `require` statement imports a module which does not exist in the source tree. Is this intended? This statement will also fail in a Node.js environment if the respective environment variable is set.

```javascript
process.env.GPXPARSE_COV ? require('./lib-cov/gpx-parse') : require('./lib/gpx-parse');
```

Maybe we could commit a skeleton directory which emulates that what will be injected by `jscoverage/JSCover`.

/André

**Comment by Wilkins** [comment]
I created a fork to browserify this module : https://github.com/Wilkins/gpx-parse
I had to hack the browserify configuration so simulate a fake lib-cov module.
It's working pretty nicely up to now. If you guys can test it to confirm everything is ok.
The resulting JS code is pretty huge though : 400kB.

**Comment by elliotstokes** [comment]
Is this something you could wrap up in a pull request or explain so I can add to the project as this has come up a few times before. 

Regarding the large file size - I'm guessing there is a reasonable amount of unexecuted js wrapped up in that file too that could be removed and the file could also be minified or is that post minification size?

**Comment by Wilkins** [comment]
Done in this PR : https://github.com/elliotstokes/gpx-parse/pull/8
The result file of 400kB is before minification. The minified version is about 150kB.

**Comment by elliotstokes** [comment]
Fixed by #8

**Comment by boldtrn** [comment]
@elliotstokes I just installed gpx-parse and had the same error using `npm install gpx-parse`.

When I run browserify I get the following error:
```
Error: Cannot find module './lib-cov/gpx-parse' from 'somewhere\node_modules\gpx-parse'
```

**Comment by elliotstokes** [comment]
Really? Did you run

      npm run browserify

I just tried and it was successful here. The dist folder should contain the latest browserified version if your are having issues.

**Comment by elliotstokes** [comment]
Essentially what I' doing is adding an alias within the grunt task.
```
dist: {
  src: 'index.js',
  dest: 'dist/gpx-parse-browser.js',
  options: {
    alias: [
      // Mockup to avoid loading lib-cov/gpx-parse in the browserify build process
      './browserify-mock.js:./lib-cov/gpx-parse'
    ]
  }
}
```


Open to other suggestions though if you have any.

**Comment by boldtrn** [comment]
@elliotstokes Running it for your repository works for me. But when I install it and add it with the above require statement to my js and run browserify on my js I get that exception.

**Comment by boldtrn** [comment]
@elliotstokes I want to add gpx-parse to my existing js. To build my js I use browserify.

I add gpx-parse to my js using: `var gpxParse = require('gpx-parse');`
I build the js using: `browserify js/main-template.js -o js/main.js`

This produces the following exception:

```
Error: Cannot find module './lib-cov/gpx-parse' from 'C:\workspace\project\node_modules\gpx-parse'
    at C:\workspace\project\node_modules\browserify\node_modules\resolve\lib\async.js:55:21
    at load (C:\workspace\project\node_modules\browserify\node_modules\resolve\lib\async.js:69:43)
    at onex (C:\workspace\project\node_modules\browserify\node_modules\resolve\lib\async.js:92:31)
    at C:\workspace\project\node_modules\browserify\node_modules\resolve\lib\async.js:22:47
    at FSReqWrap.oncomplete (fs.js:82:15)
```

**Comment by elliotstokes** [comment]
You need to set up an alias for the missing file and use the browserify-mock.js file instead. I'm doing it wild gulp in my build. I'm not sure of the correct parameters on the browserify cli.

**Comment by boldtrn** [comment]
@elliotstokes Thanks. I tried with aliasify, but wasn't able to do it. For now I just changed the require statement in your index.js. I might try again in the future.

Thanks for your work and your help!
