### ISSUE TITLE
Reverse operation

### ISSUE THREAD

**Issue by Wilkins** [elliotstokes/gpx-parse#7]
I'm trying to use your GPX Parser in one of my project : https://github.com/Wilkins/gpx-simplify-optimizer
In the project, I simplify a geometry to reduce the number of points in a track/segment.
Your parser is working nicely. But I would like to know if there is a way to put the GPX data back into a XML string ? Either with your project, or maybe with another NodeJS library.
Thanks

**Comment by elliotstokes** [comment]
ah nice idea! It's not something I have implemented a currently but it should be pretty simple to implement.

**Comment by Wilkins** [comment]
Great. I found a module that kinda does it already : https://github.com/kchapelier/gpx
Maybe this could help you.
